name: test

on:
  push:
    branches: [ master, development, feature/*, bugfix/*, maintenance/* ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    
    container: python:${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Test with pytest
        run: |
          poetry run coverage run --source=eventipy -m py.test tests/unit
      - name: Upload to coveralls
        run: |
          poetry run coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
